<a href="https://colab.research.google.com/github/avanniiii/AvaniAgarwal_102303745_UML501/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Avani Agarwal, 102303745


Assignment-1

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [6]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
reversed_arr=arr[::-1]
print("Reversed Array:",reversed_arr)

Reversed Array: [5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods


In [7]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1=array1.flatten()
print("Flatten using flatten():",flat1)
flat2=array1.ravel()
print("Flatten using ravel():",flat2)

Flatten using flatten(): [1 2 3 2 4 5 1 2 3]
Flatten using ravel(): [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [8]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comp=np.array_equal(arr1,arr2)
print(comp)

True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [10]:
#(i)
x=np.array([1,2,3,4,5,1,2,1,1,1])
vals_x,count_x=np.unique(x,return_counts=True)
most_frequent_x=vals_x[np.argmax(count_x)]
indices_x=np.where(x==most_frequent_x)[0]
print("Most frequent value in x:",most_frequent_x,"Indices:",indices_x)


#(ii)
y=np.array([1,1,1,2,3,4,2,4,3,3])
vals_y,count_y=np.unique(y,return_counts=True)
most_frequent_y=vals_y[np.argmax(count_y)]
indices_y=np.where(y==most_frequent_y)[0]
print("Most frequent value in y:",most_frequent_y,"Indices:",indices_y)

Most frequent value in x: 1 Indices: [0 5 7 8 9]
Most frequent value in y: 1 Indices: [0 1 2]


(e)For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i.   Sum of all elements

ii.  Sum of all elements row-wise

iii. Sum of all elements column-wise





In [12]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

#(i)
tot_sum=gfg.sum()
print("Sum of all elements:",tot_sum)

#(ii)
row_sum=gfg.sum(axis=1)
print("Sum of all elements row-wise:\n",row_sum)

#(iii)
col_sum=gfg.sum(axis=0)
print("Sum of all elements column-wise:\n",col_sum)

Sum of all elements: 45
Sum of all elements row-wise:
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:
 [[20  9 16]]


(f)For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [14]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])

#(i)
diagonal_sum=np.trace(n_array)
print("Sum of diagonal elements:",diagonal_sum)

#(ii) (iii)
eigen_vals,eigen_vecs=np.linalg.eig(n_array)
print("Eigen values of matrix:\n",eigen_vals)
print("Eigen vectors of matrix:\n",eigen_vecs)

#(iv)
inv_matrix=np.linalg.inv(n_array)
print("Inverse of matrix:\n",inv_matrix)

#(v)
det_val=np.linalg.det(n_array)
print("Determinant of matrix:",det_val)

Sum of diagonal elements: 176
Eigen values of matrix:
 [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


(g)Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [16]:
#(i)
p1=np.array([[1,2],[2,3]])
q1=np.array([[4,5],[6,7]])
prod1=np.dot(p1,q1)
cov1=np.cov(p1,rowvar=False)

print("Matrix Multiplication1:\n",prod1)
print("Covariance1:\n",cov1)

#(ii)
p2=np.array([[1, 2], [2, 3], [4, 5]])
q2=np.array([[4, 5, 1], [6, 7, 2]])
prod2=np.dot(p2,q2)
cov2=np.cov(p2,rowvar=False)

print("Matrix Multiplication1:\n",prod2)
print("Covariance1:\n",cov2)

Matrix Multiplication1:
 [[16 19]
 [26 31]]
Covariance1:
 [[0.5 0.5]
 [0.5 0.5]]
Matrix Multiplication1:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance1:
 [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


(h)For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [17]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])

#Inner product
inner=np.inner(x,y)

#Outer product
outer=np.outer(x.flatten(),y.flatten())

#Cartesian product
from itertools import product
cartesian=np.array(list(product(x.flatten(),y.flatten())))

print("Inner:\n",inner)
print("Outer:\n",outer)
print("Cartesian:\n",cartesian)

Inner:
 [[17 52]
 [13 62]]
Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [20]:
array=np.array([[1,-2,3],[-4,5,-6]])

#(i)
abs_val=np.abs(array)
print("Element-wise absolute value:\n",abs_val)


#(ii)
flatten_array=array.flatten()
p25=np.percentile(flatten_array,25)
p50=np.percentile(flatten_array,50)
p75=np.percentile(flatten_array,75)

percentile_col=np.percentile(array,[25,50,75],axis=0)
percentile_row=np.percentile(array,[25,50,75],axis=1)
print("Flattened Percentiles: 25% =", p25, ", 50% =", p50, ", 75% =", p75)
print("Column Percentiles:\n", percentile_col)
print("Row Percentiles:\n", percentile_row)

#(iii)
mean=np.mean(flatten_array)
median=np.median(flatten_array)
sd=np.std(flatten_array)
print("Mean:", mean, "Median:", median, "Standard Deviation:", sd)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Flattened Percentiles: 25% = -3.5 , 50% = -0.5 , 75% = 2.5
Column Percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row Percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean: -0.5 Median: -0.5 Standard Deviation: 3.8622100754188224


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [21]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])

print("Floor:",np.floor(a))
print("Ceil:",np.ceil(a))
print("Truncated Value:",np.trunc(a))
print("Rounded Values:",np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Value: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [22]:
arr=np.array([10,52,62,16,16,54,453])

#(i)
sorted_arr=np.sort(arr)
print("Sorted array:", sorted_arr)

#(ii)
indices=np.argsort(arr)
print("Indices of sorted array:", indices)

#(iii)
smallest=np.sort(arr)[:4]
print("4 Smallest elements:", smallest)

#(iv)
largest=np.sort(arr)[-5:]
print("5 Largest elements:", largest)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 Smallest elements: [10 16 16 52]
5 Largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [27]:
arr=np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

#(i)
int_elements=array[arr == arr.astype(int)]
print("Integer Elements:", int_elements)


#(ii)
float_elements=array[arr != arr.astype(int)]
print("Float Elements:", float_elements)

Integer Elements: [1. 2. 3. 2.]
Float Elements: [1.2 2.2]


Q4:

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [43]:
from google.colab import files
uploaded = files.upload()

Saving flowerr.png to flowerr (2).png


In [44]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)

    arr = np.array(img)

    if arr.ndim == 2:
        print("Grayscale Image Detected")
    elif arr.ndim == 3:
        print("RGB Image Detected")
    else:
        print("Unknown format")

    np.savetxt("image_array.txt", arr.reshape(-1, arr.shape[-1]) if arr.ndim == 3 else arr, fmt='%d')
    print("Saved as image_array.txt")

img_to_array("flowerr.png")

RGB Image Detected
Saved as image_array.txt


(b) Load the saved file into jupyter notebook?

In [45]:
loaded = np.loadtxt("image_array.txt", dtype=int)

print("Loaded array shape:", loaded.shape)
print(loaded)

Loaded array shape: (252824, 4)
[[181 189 209 255]
 [182 191 209 255]
 [183 191 209 255]
 ...
 [ 16  33   4 255]
 [ 27  57  56 255]
 [ 47 104 131 255]]
